"""Shared servo config/helpers for clock_daemon.py and servo_test.py.

Uses lgpio (talks to /dev/gpiochip0 via the kernel GPIO character device) -
no background daemon needed.

IMPORTANT - lgpio must be imported with a WRITABLE working directory. On
import it spawns a notify thread that creates a '.lgd-nfy<n>' file in the cwd,
so running from a read-only directory (e.g. /) dies with:
    FileNotFoundError: [Errno 2] ... '.lgd-nfy-3'
This is why the systemd unit sets WorkingDirectory to the project folder.

IMPORTANT - two lgpio behaviours that differ from pigpio:
  1. A pin must be claimed as an output (gpio_claim_output) before tx_servo
     will drive it. pigpio did not require this.
  2. The pulse train is generated by a thread INSIDE this process. It stops
     the moment the process exits or the chip handle is closed. pigpio's
     daemon kept pulsing after your script exited; lgpio does not. Anything
     that sets an angle must stay alive for as long as it wants the servo held.
"""
import time

try:
    import lgpio
except ImportError:
    lgpio = None

SERVO_PINS = {"dad": 19, "lachlan": 18, "mum": 13, "stella": 12}  # BCM pin numbers
PULSE_MIN_US = 500   # pulsewidth at 0 degrees
PULSE_MAX_US = 2500  # pulsewidth at 180 degrees
SERVO_FREQ_HZ = 50
GPIO_CHIP = 0  # /dev/gpiochip0 - header GPIOs on Pi 3/4. (Pi 5 moves these to chip 4.)


def angle_to_pulsewidth(angle_deg):
    angle_deg = max(0, min(180, angle_deg))
    return int(PULSE_MIN_US + (angle_deg / 180) * (PULSE_MAX_US - PULSE_MIN_US))


def connect(pins=None):
    """Open the GPIO chip and claim each servo pin as an output.

    Returns a handle to pass into set_pulsewidth/disconnect.
    """
    if lgpio is None:
        raise SystemExit("[!] lgpio not installed. Try: sudo apt install python3-lgpio "
                         "(and create the venv with --system-site-packages)")
    try:
        handle = lgpio.gpiochip_open(GPIO_CHIP)
    except Exception as e:
        raise SystemExit(f"[!] Could not open /dev/gpiochip{GPIO_CHIP}: {e}")

    for pin in (SERVO_PINS.values() if pins is None else pins):
        rc = lgpio.gpio_claim_output(handle, pin)
        if rc < 0:
            raise SystemExit(
                f"[!] Could not claim GPIO {pin} as output (error {rc}). "
                "Another process may be holding it."
            )
    return handle


def set_pulsewidth(handle, pin, pulsewidth_us):
    """pulsewidth_us=0 stops sending pulses (servo relaxes).

    Remember: pulses only continue while this process is alive.
    """
    rc = lgpio.tx_servo(handle, pin, int(pulsewidth_us), SERVO_FREQ_HZ)
    if rc < 0:
        print(f"[!] lgpio.tx_servo(pin={pin}, us={pulsewidth_us}) failed with error {rc}")
    return rc


def set_angle(handle, pin, angle_deg):
    return set_pulsewidth(handle, pin, angle_to_pulsewidth(angle_deg))


def disconnect(handle, pins=None):
    for pin in (SERVO_PINS.values() if pins is None else pins):
        try:
            lgpio.tx_servo(handle, pin, 0)  # stop pulsing, let the servo relax
            lgpio.gpio_free(handle, pin)
        except Exception:
            pass
    lgpio.gpiochip_close(handle)


def bitbang(handle, pin, pulse_us, seconds=2.0, freq=SERVO_FREQ_HZ):
    """Generate a servo pulse train by hand with plain gpio_write calls.

    Deliberately bypasses tx_servo entirely. Since plain high/low writes are
    already proven to reach the motor, if this moves the servo and tx_servo
    does not, the fault is in tx_servo/how it is being called - not wiring,
    power, permissions or the pin.
    """
    period = 1.0 / freq
    pulse_s = pulse_us / 1_000_000.0
    end = time.perf_counter() + seconds
    while time.perf_counter() < end:
        t0 = time.perf_counter()
        lgpio.gpio_write(handle, pin, 1)
        while time.perf_counter() - t0 < pulse_s:  # busy-wait: sleep() is too coarse at 1-2ms
            pass
        lgpio.gpio_write(handle, pin, 0)
        time.sleep(max(0.0, period - (time.perf_counter() - t0)))
